<?php
$mrożonki_łódzkie = array (
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,,%C5%82%C3%B3d%C5%BA,g%C3%B3rna,kili%C5%84skiego,210/gastropak_opakowania_jednorazowe-sfamyu_fdf.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,,%C5%82%C3%B3d%C5%BA,g%C3%B3rna,kurczaki,131/cajdex_grzyby_i_owoce_mrozone_suszone-scxcjr_ssj.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,sieradzki,br%C4%85szewice,g%C3%B3rna,8/ab_frost_sp._j._krolik-oyyock_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,%C5%82owicki,b%C5%82%C4%99d%C3%B3w,32/annal_anna_malczyk-knklx_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,tomaszowski,tomasz%C3%B3w_mazowiecki,zgorzelicka,29_31/asmir_sp.j._hurtownia-nykyg_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,wieruszowski,wierusz%C3%B3w,teklinowska,29/augusto_wieruszow_s.c._anna_zimoch_andrzej_zimoch_magdalena_zimoch-kaare_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,radomszcza%C5%84ski,radomsko,d%C4%85browskiej,108/augusto_topaz_hurtownia_mrozonek_andrzej_ciszewski-ppmwi_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,%C5%82owicki,jackowice,83/gabriel_siurek_iglomar-awdwed_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,pabianicki,pabianice,rypu%C5%82towicka,50a/mador_sp._z_o.o.-odempi_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,sieradzki,sieradz,podg%C3%B3rze,9/marco_producent_mrozonek_marlena_kaminska-zwljra_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,sieradzki,stawiszcze/mark_bud_sp._z_o.o._zaklad_produkcji_spozywczej-pzsws_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,,%C5%82%C3%B3d%C5%BA,ba%C5%82uty,rumu%C5%84ska,13b/polfruta_agnieszka_moczynska-kpkfw_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,paj%C4%99cza%C5%84ski,paj%C4%99czno,krucza,7/ppuh_haga_s.c.-mwweh_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,piotrkowski,gorzkowice,przedborska,27/rollux_sp._z_o.o._sp._k.-kjrjb_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,sieradzki,kamionka,48/ser_wika_s.c._przedsiebiorstwo_wielobranzowe_hurtownia-pwgml_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,,%C5%82%C3%B3d%C5%BA,ferdynanda_ossendowskiego,7/testom_sp._z_o.o.-zgjwlf_suh.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,zgierski,zgierz,dygasi%C5%84skiego,29/intesmak_zaklad_produkcyjno_handlowo_uslugowy-sfwerg_stt.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,kutnowski,kutno,krasi%C5%84skiego,56/hurtownia_sniezka_lody_i_mrozonki_opakowania_jednorazowe_do_gastronomii-pftzb_fdf.html",
"https://panoramafirm.pl/%C5%82%C3%B3dzkie,opoczy%C5%84ski,opoczno,staromiejska,70/yeti_hurtownia_mrozonek_a._i_m._chochowska-ndrwf_suk.html",
)
?>