<?php
$fotowoltaika = array (
"https://www.baza-firm.com.pl/fotowoltaika/sanok/global-sun/pl/78023.html",
"https://www.baza-firm.com.pl/fotowoltaika/krakow/lmv-group-sp-z-oo/pl/367718.html",
"https://www.baza-firm.com.pl/fotowoltaika/wlodawa/przedsiebiorstwo-uslugowo-handlowe-energetyk-spj/pl/327846.html",
"https://www.baza-firm.com.pl/fotowoltaika/katowice/ameripol-trading-ltd-sp-z-oo/pl/8978.html",
"https://www.baza-firm.com.pl/fotowoltaika/radomsko/antronik/pl/218183.html",
"https://www.baza-firm.com.pl/fotowoltaika/rzeszow/basmac-sp-z-oo/pl/26157.html",
"https://www.baza-firm.com.pl/fotowoltaika/krakow/bisolar-energy-fotowoltaika/pl/377642.html",
"https://www.baza-firm.com.pl/fotowoltaika/miedzyrzecze/eco-system/pl/356347.html",
"https://www.baza-firm.com.pl/fotowoltaika/tuchola/enerkan-fotowoltaika/pl/375618.html",
"https://www.baza-firm.com.pl/fotowoltaika/olesno/fhu-jacek-bak-sp-z-oo/pl/160158.html",
"https://www.baza-firm.com.pl/fotowoltaika/choroszcz/marand-apolkosnik-spkomandytowa/pl/179960.html",
"https://www.baza-firm.com.pl/fotowoltaika/kraszewice/pg-system/pl/123563.html",
"https://www.baza-firm.com.pl/fotowoltaika/sanok/przedsiebiorstwo-budowlane-elbud-czeslaw-stasicki/pl/70457.html",
"https://www.baza-firm.com.pl/fotowoltaika/krakow/solar-tracker-polska-gwalbert-stefanski/pl/69429.html",
"https://www.baza-firm.com.pl/fotowoltaika/koszalin/aiseo-piotr-maliszewski/pl/346893.html",
"https://www.baza-firm.com.pl/fotowoltaika/piekary-slaskie/ekopol-energy/pl/381056.html",
"https://www.baza-firm.com.pl/fotowoltaika/imielin/fotowoltaika-rafal-michal-nowrocki/pl/365098.html",
"https://www.baza-firm.com.pl/fotowoltaika/rzeszow/mldystrybucja/pl/375977.html",
"https://www.baza-firm.com.pl/fotowoltaika/katowice/rensan-energy-sp-z-oo/pl/306488.html",
"https://www.baza-firm.com.pl/fotowoltaika/dabrowka/sunlightpro-maciej-domanski/pl/378387.html",
)
?>